### ISSUE TITLE
No module named 'faq'

### ISSUE THREAD

**Issue by pors** [smark-1/django-easy-faq#1]
Hi!

I followed your instructions, but when starting the server I get `ModuleNotFoundError: No module named 'faq'`

I did install it:
```
pip freeze | fgrep faq
django-easy-faq==1.1
```

Any idea?

**Comment by smark-1** [comment]
This was an issue for an older version of this app. I will have to look into this for version 1.1.
Thanks for reporting

**Comment by smark-1** [comment]
Can you send me a copy of the installed apps setting?

**Comment by pors** [comment]
When I print it I get:

```
['django.contrib.auth', 'django.contrib.contenttypes', 'django.contrib.sessions', 'django.contrib.sites', 'django.contrib.messages', 'django.contrib.staticfiles', 'django.contrib.admin', 'django.forms', 'django_filters', 'crispy_forms', 'faq']
```

Is that what you are looking for?

**Comment by smark-1** [comment]
yes

**Comment by smark-1** [comment]
I think I fixed the issue please install the newest release from pypi django-easy-faq==1.2
please let me know if this works

**Comment by pors** [comment]
It does, thanks!
