### ISSUE TITLE
support for login protected FAQs

### ISSUE THREAD

**Issue by arcturusannamalai** [smark-1/django-easy-faq#10]
currently the FAQs are visible to all users of the site including un-authenticated ones.

**Comment by smark-1** [comment]
Most website want the FAQ to be visible to all users even if they are not logged in. For this to change it must be a setting/flag that the website can set.

**Comment by arcturusannamalai** [comment]
OK - let me do that; thanks for feedback

**Comment by arcturusannamalai** [comment]
@dragoncommits - updated with a "login_required" FAQ_SETTINGS option.
