### ISSUE TITLE
Adding screenshots, demo link or example dir with ready-to-use faq-app

### ISSUE THREAD

**Issue by markheckmann** [smark-1/django-easy-faq#14]
Hi,

thanks for your faq-app. :)

**One wish:** It would be great if you could add some screenshots, a link to a short YoutTube video, or a demo link (if exists) to the README. On top, maybe an /example directory with a ready-to-use Django clonable FAQ project (including fixtures etc.) to get started right away would be great. 

**Reason**: Currently, I am just trying to figure out, if the faq-app is what I am looking for. To do this, I seem to have to go through the process of setting up the app locally, adding some dummy data, etc. This is quite a lot just to explore the features and see if the app is what I am actually looking for. I guess many people might just jump off at that point.

Or am I just missing something and all this already exist? :)

Thanks!
Mark

**Comment by smark-1** [comment]
Great Idea! I added screenshots in a markdown file. The link is in the readme file. These screenshots are using Bootstrap 5 styles. Any suggestions would be appreciated.

**Comment by markheckmann** [comment]
Thanks a lot. That already really helps! Currently, I do not have further suggestions. :)
