### ISSUE TITLE
Test returns error `TypeError: 'NoneType' object is not subscriptable` in `QuestionDetail` View

### ISSUE THREAD

**Issue by rafadan2** [smark-1/django-easy-faq#24]
The `QuestionDetail` view does not set the `can_vote_question` and `can_vote_answer` context variables, which causes a `TypeError` when running tests that expect these variables to be present.

**Comment by smark-1** [comment]
Can you provide a full traceback of the error?
What version of python/django and django-easy-faq you are using and what faq settings are being used?

**Comment by smark-1** [comment]
I haven't been able to reproduce this error
