### ISSUE TITLE
Support for multiline answers

### ISSUE THREAD

**Issue by frlan** [smark-1/django-easy-faq#9]
It would be nice if answers would support multiline and other markup things and documenation helps users to make usage of it

**Comment by smark-1** [comment]
What other markup should it support?

**Comment by frlan** [comment]
I can imagine of

- multiline/paragraphs 
- lists
- some picture (upload maybe not needed)

**Comment by smark-1** [comment]
So maybe add an optional wysiwyg editor support like [tinymce](https://github.com/jazzband/django-tinymce). If the optional tinymce editor is installed then a setting could to display the rich text editor.

**Comment by smark-1** [comment]
@frlan is #18 what you mean?

**Comment by frlan** [comment]
Not sure whetehr we need an tinemce here -- but from user side yepp … this is helping a lot. Thx. 
I did only scroll over the diff so far -- is there tinymce support also available in admin backend? I might missed out that part ;)

**Comment by smark-1** [comment]
tinymce support is not yet available for the django admin. Hope to add that soon.

**Comment by smark-1** [comment]
Added tinymce support to the admin

**Comment by frlan** [comment]
@smark-1 Nice -- will give it a try soonish. Thanks

**Comment by frlan** [comment]
Looks nice -- thanks!
